language: java
jdk:
- oraclejdk8
install: true
script:
- gradle zipMap
before_deploy:
- git config --global user.email "tripleabuilderbot@gmail.com" 
- git config --global user.name "tripleabuilderbot"
- export MAP_TAGGED_VERSION="$MAP_VERSION.$TRAVIS_BUILD_NUMBER"
- git tag $MAP_TAGGED_VERSION -a -m "$MAP_TAGGED_VERSION"
- git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-maps/$REPO_NAME --tags
deploy:
  provider: releases
  api_key:
    secure: BlvJuaJb7Id4W7gaiqoFW1D7/NLjCwk7rIGJETNyPeTRJss9wk/0uj7RXUWggTNkUQkVH5Sf6WyvUuxe7Fizn+SND/QimCLtFowNGchhwE2npyKqe9SIC5NSF9gkyV/B0M+2kPGvvMtUox4ENu7gl4usN4HPOmxunYUXxXpO48qjjEz/RLnVILNOmukeXCKJd9cET6pDsByeGDKT7zkzU0nVAuz/EfIX0PoqfYgPc/PeTd5DB8rF8KSIE1HxikQqRGnQMeaLHPbL6xm5LzFWCNQQLFfjGO7ecO1xQ3VKwTunzt7xT5nNa/RP3CdF4t+kc5fwlLFtzmj1Bt2dVTo1xA8SSMG8pJfdJ9gpgyNjI+1RHHMdHTinBGKjU9rkGcKp20i9I8QCNAZWx06lXu75JfX/XzqdC/QO3BZXeD/PlITjLpRvyvEMUO1+sTvBR7cB1jFd59C27wbuuG1zXLHj0zCJytOrvqhvui1dXbwKZRfflg9KuTTMicbfzbd2bJQaBOshYDU0KsPjxyQARCNM+gnsfcIYYs+8tsiL9ay8AIB2Ppu+w0x7ZubJvGO51PtsT8oiXlgZIOo1Nz+hsCeO7z2FsBB36xQc7siF8skVgYbzmjrgTWETIe0a6dzgxcQduoiWMLeGH1y2Kjd83oflYv6OGjF4EiTYlh1t9bj94aE=
  file: "$REPO_NAME.zip"
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    all_branches: true
